# Generated by Django 6.0.2 on 2026-02-26 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Seller', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Seller', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
