# Generated by Django 6.0.2 on 2026-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_seller_alter_carlisting_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20),
        ),
    ]
