# Generated by Django 6.0.2 on 2026-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_brand_discoverypill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverypill',
            name='pill_type',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Body Type', 'Body Type'), ('Fuel Type', 'Fuel Type'), ('Transmission', 'Transmission')], default='Budget', max_length=20),
        ),
    ]
