# Generated by Django 6.0.2 on 2026-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_discoverypill_pill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
        ),
    ]
