# Generated by Django 6.0.2 on 2026-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_seating_capacity_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
