# Generated by Django 6.0.2 on 2026-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration_0_100',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='safety_rating',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='three_d_model_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='torque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
